apiVersion: v1
data:
  enable-vts-status: "true"
  vts-default-filter-key: "$server_name"
  client-max-body-size: 100m
  proxy-body-size: 100m
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: ingress-nginx
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: ingress-nginx
