apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-external
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 31080
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: ingress-nginx-external
